package com.frackowiak.database.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.frackowiak.database.dao.Player;

import com.frackowiak.database.dao.Achievement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ACHIEVEMENT.
*/
public class AchievementDao extends AbstractDao<Achievement, Long> {

    public static final String TABLENAME = "ACHIEVEMENT";

    /**
     * Properties of entity Achievement.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "Name", false, "NAME");
        public final static Property Description = new Property(2, String.class, "Description", false, "DESCRIPTION");
        public final static Property Condition = new Property(3, String.class, "Condition", false, "CONDITION");
        public final static Property IsAchieved = new Property(4, Boolean.class, "IsAchieved", false, "IS_ACHIEVED");
        public final static Property PlayerId = new Property(5, Long.class, "PlayerId", false, "PLAYER_ID");
    };

    private DaoSession daoSession;


    public AchievementDao(DaoConfig config) {
        super(config);
    }
    
    public AchievementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ACHIEVEMENT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: Name
                "'DESCRIPTION' TEXT," + // 2: Description
                "'CONDITION' TEXT," + // 3: Condition
                "'IS_ACHIEVED' INTEGER," + // 4: IsAchieved
                "'PLAYER_ID' INTEGER);"); // 5: PlayerId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ACHIEVEMENT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Achievement entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(2, Name);
        }
 
        String Description = entity.getDescription();
        if (Description != null) {
            stmt.bindString(3, Description);
        }
 
        String Condition = entity.getCondition();
        if (Condition != null) {
            stmt.bindString(4, Condition);
        }
 
        Boolean IsAchieved = entity.getIsAchieved();
        if (IsAchieved != null) {
            stmt.bindLong(5, IsAchieved ? 1l: 0l);
        }
 
        Long PlayerId = entity.getPlayerId();
        if (PlayerId != null) {
            stmt.bindLong(6, PlayerId);
        }
    }

    @Override
    protected void attachEntity(Achievement entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Achievement readEntity(Cursor cursor, int offset) {
        Achievement entity = new Achievement( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Description
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Condition
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // IsAchieved
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // PlayerId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Achievement entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCondition(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsAchieved(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setPlayerId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Achievement entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Achievement entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPlayerDao().getAllColumns());
            builder.append(" FROM ACHIEVEMENT T");
            builder.append(" LEFT JOIN PLAYER T0 ON T.'PLAYER_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Achievement loadCurrentDeep(Cursor cursor, boolean lock) {
        Achievement entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Player player = loadCurrentOther(daoSession.getPlayerDao(), cursor, offset);
        entity.setPlayer(player);

        return entity;    
    }

    public Achievement loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Achievement> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Achievement> list = new ArrayList<Achievement>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Achievement> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Achievement> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
