package com.frackowiak.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BEACON.
 */
public class Beacon {

    private Long id;
    private String UUID;
    private String MACAddress;
    private String Major;
    private String Minor;
    private String Location;

    public Beacon() {
    }

    public Beacon(Long id) {
        this.id = id;
    }

    public Beacon(Long id, String UUID, String MACAddress, String Major, String Minor, String Location) {
        this.id = id;
        this.UUID = UUID;
        this.MACAddress = MACAddress;
        this.Major = Major;
        this.Minor = Minor;
        this.Location = Location;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUUID() {
        return UUID;
    }

    public void setUUID(String UUID) {
        this.UUID = UUID;
    }

    public String getMACAddress() {
        return MACAddress;
    }

    public void setMACAddress(String MACAddress) {
        this.MACAddress = MACAddress;
    }

    public String getMajor() {
        return Major;
    }

    public void setMajor(String Major) {
        this.Major = Major;
    }

    public String getMinor() {
        return Minor;
    }

    public void setMinor(String Minor) {
        this.Minor = Minor;
    }

    public String getLocation() {
        return Location;
    }

    public void setLocation(String Location) {
        this.Location = Location;
    }

}
