package com.frackowiak.database.dao;

import com.frackowiak.database.db.DaoSession;
import de.greenrobot.dao.DaoException;

import com.frackowiak.database.db.ConfigurationDao;
import com.frackowiak.database.db.PlayerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONFIGURATION.
 */
public class Configuration {

    private Long id;
    private String Name;
    private Long ErrandInterval;
    private Long PlayerId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ConfigurationDao myDao;

    private Player player;
    private Long player__resolvedKey;


    public Configuration() {
    }

    public Configuration(Long id) {
        this.id = id;
    }

    public Configuration(Long id, String Name, Long ErrandInterval, Long PlayerId) {
        this.id = id;
        this.Name = Name;
        this.ErrandInterval = ErrandInterval;
        this.PlayerId = PlayerId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getConfigurationDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public Long getErrandInterval() {
        return ErrandInterval;
    }

    public void setErrandInterval(Long ErrandInterval) {
        this.ErrandInterval = ErrandInterval;
    }

    public Long getPlayerId() {
        return PlayerId;
    }

    public void setPlayerId(Long PlayerId) {
        this.PlayerId = PlayerId;
    }

    /** To-one relationship, resolved on first access. */
    public Player getPlayer() {
        Long __key = this.PlayerId;
        if (player__resolvedKey == null || !player__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PlayerDao targetDao = daoSession.getPlayerDao();
            Player playerNew = targetDao.load(__key);
            synchronized (this) {
                player = playerNew;
            	player__resolvedKey = __key;
            }
        }
        return player;
    }

    public void setPlayer(Player player) {
        synchronized (this) {
            this.player = player;
            PlayerId = player == null ? null : player.getId();
            player__resolvedKey = PlayerId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
