package com.frackowiak.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEAM.
 */
public class Team {

    private Long id;
    private String Name;
    private Integer Points;

    public Team() {
    }

    public Team(Long id) {
        this.id = id;
    }

    public Team(Long id, String Name, Integer Points) {
        this.id = id;
        this.Name = Name;
        this.Points = Points;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getPoints() {
        return Points;
    }

    public void setPoints(Integer Points) {
        this.Points = Points;
    }

}
