package com.frackowiak.database.dao;

import com.frackowiak.database.db.DaoSession;
import de.greenrobot.dao.DaoException;

import com.frackowiak.database.db.DayDao;
import com.frackowiak.database.db.PlayerDao;
import com.frackowiak.database.db.WorkDayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WORK_DAY.
 */
public class WorkDay {

    private Long id;
    private String Name;
    private java.util.Date Date;
    private Long PlayerId;
    private Long DayId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient WorkDayDao myDao;

    private Player player;
    private Long player__resolvedKey;

    private Day day;
    private Long day__resolvedKey;


    public WorkDay() {
    }

    public WorkDay(Long id) {
        this.id = id;
    }

    public WorkDay(Long id, String Name, java.util.Date Date, Long PlayerId, Long DayId) {
        this.id = id;
        this.Name = Name;
        this.Date = Date;
        this.PlayerId = PlayerId;
        this.DayId = DayId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getWorkDayDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public java.util.Date getDate() {
        return Date;
    }

    public void setDate(java.util.Date Date) {
        this.Date = Date;
    }

    public Long getPlayerId() {
        return PlayerId;
    }

    public void setPlayerId(Long PlayerId) {
        this.PlayerId = PlayerId;
    }

    public Long getDayId() {
        return DayId;
    }

    public void setDayId(Long DayId) {
        this.DayId = DayId;
    }

    /** To-one relationship, resolved on first access. */
    public Player getPlayer() {
        Long __key = this.PlayerId;
        if (player__resolvedKey == null || !player__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PlayerDao targetDao = daoSession.getPlayerDao();
            Player playerNew = targetDao.load(__key);
            synchronized (this) {
                player = playerNew;
            	player__resolvedKey = __key;
            }
        }
        return player;
    }

    public void setPlayer(Player player) {
        synchronized (this) {
            this.player = player;
            PlayerId = player == null ? null : player.getId();
            player__resolvedKey = PlayerId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Day getDay() {
        Long __key = this.DayId;
        if (day__resolvedKey == null || !day__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DayDao targetDao = daoSession.getDayDao();
            Day dayNew = targetDao.load(__key);
            synchronized (this) {
                day = dayNew;
            	day__resolvedKey = __key;
            }
        }
        return day;
    }

    public void setDay(Day day) {
        synchronized (this) {
            this.day = day;
            DayId = day == null ? null : day.getId();
            day__resolvedKey = DayId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
